import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Date;

/**
 * @author Nicolas Dionne
 *
 */
public class GUI_AjoutLocation extends GUI {
	final JPanel panel1 = new JPanel();
	private JList<Vehicule> jListeVehicule;
	private ArrayList<Vehicule> listeVehicule;
	private JButton confirmerButton;
	private JButton annulerButton;

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 */
	public GUI_AjoutLocation(GUI upperMenu) {
		boolean abort = false;
		this.upperMenu = upperMenu;
		// Initialisation de la JList
		abort = !JListInitilisation();
		//L'utilisateur indique surement qu'il veut annuler l'ajout d'une location
		if(abort)
			return ;//On interompe la création de l'interface
		
		// Initialisation des variables
		frame = new JFrame("Formulaire ajout client");
		
		//Configuration de l'interface
		panel1.setLayout(new BorderLayout(0, 0));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new BorderLayout(0, 0));
		panel1.add(panel2, BorderLayout.WEST);
		final JScrollPane scrollPane1 = new JScrollPane();
		panel2.add(scrollPane1, BorderLayout.CENTER);
		scrollPane1.setViewportView(jListeVehicule);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new BorderLayout(0, 0));
		panel1.add(panel3, BorderLayout.EAST);
		
		//Configuration Bouton pour annuler
		annulerButton = new JButton();
		annulerButton.setText("Annuler");
		annulerButton.addActionListener(e -> annulerButtonClick());
		panel3.add(annulerButton, BorderLayout.SOUTH);
		
		//Configuration Bouton pour confirmer
		confirmerButton = new JButton();
		confirmerButton.setText("Confirmer");
		confirmerButton.addActionListener(e -> confirmerButtonClick());
		panel1.add(confirmerButton, BorderLayout.SOUTH);
		
		//Texte indiquant de séléctionner un véhicule
		final JLabel label1 = new JLabel();
		label1.setText("Veuiller selectionner un vehicule");
		panel1.add(label1, BorderLayout.NORTH);

		// JFrame initialisation
		upperMenu.hide();
		frame.setContentPane(panel1);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
		frame.setSize(400, 300);
	}
	/**
	 * 
	 * Event se produisant lorsqu'on presse sur le bouton : "Confirmer"
	 */
	private void confirmerButtonClick() {
		Vehicule vehicSelectionner;
		vehicSelectionner = listeVehicule.get(jListeVehicule.getSelectedIndex());
		
		String contrat;
		//Appelle du registre pour la sélection du véhicule
		contrat = RegistreLocation.SelectionVehicule(vehicSelectionner);
		
		//Formatage des choix d'option pour confirmer ou annuler location
		String[] options = {"Confirmer","Annuler"};
		int choixUtilisateur;
		choixUtilisateur = JOptionPane.showOptionDialog(null, contrat, "Contrat de location", JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE, null, options, options[0]); 
		
		//On vérifie si l'utilisateur confirme
		if(choixUtilisateur == 0)
			//On appelle la méthode du registre traitant la partie 4 du cas 7 Ajouter une location
			this.showMessage(RegistreLocation.confirmationLocation(), "Confirmation de location");
		
		//Si l'utilisateur veut annuler
		else 
			this.toUpperMenu();
	}

	/**
	 * 
	 * Event se produisant lorsqu'on presse sur le bouton : "Annuler"
	 */
	private void annulerButtonClick() {
		this.toUpperMenu();
	}

	
	/**@author Nicolas Dionne
	 * 
	 * Methode ayant pour but d'initialiser la JList afin qu'elle puisse être afficher
	 * @return true si tout c'est bien passer, false si la création doit etre aborter.
	 */
	private boolean JListInitilisation() {
		boolean toutEstBeau = true;
		int noReser;
		// Tant que l'utilisateur ne veut pas quitter ou qu'il entre de mauvaise réponse
		do {
			noReser = this.inputBoxInt("Veuillez entrer le numero de reservation ", "Ajout Location");
			// On traite l'entrer
			if (noReser == -1)// Si l'utilisateur veut annuler
				{
				this.cancelCreation();
				return false;
				}
				
			else {
				// On va fetch la liste des vehicule par le registre
				listeVehicule = RegistreLocation.SaisiNoReservation(noReser);

				// Si elle n'est pas nulle
				if (listeVehicule != null) {
					// On la transforme pour la JList
					String[] tab = new String[listeVehicule.size()];
					// Petit formatage pour la JList precisement
					for (int i = 0; i < listeVehicule.size(); i++)
						tab[i] = listeVehicule.get(i).getCategorie() + " " + listeVehicule.get(i).getKilometrage()
								+ listeVehicule.get(i).getDate();
					jListeVehicule = new JList(tab);
				}
				// Sinon, On affiche l'erreur et on recommence
				else
				{
					toutEstBeau = false;
					showMessage("Une erreur c'est produit nous avons pas pu trouver votre \n réservation avec le numéro de réservation entrer", "Message d'erreur");
				}
			}
		} while (!toutEstBeau);
		return toutEstBeau;

	}
}
