import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Date;
/**
 * @author Nicolas Dionne
 *
 */
public class GUI_AjoutLocation extends GUI {
	final JPanel panel1 = new JPanel();
	private JList list1;
    private JButton confirmerButton;
    private JButton annulerButton;
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     */
    public GUI_AjoutLocation(GUI upperMenu)
	{ 	
    	//Initialisation de la JList
	     JListInitilisation();
    	//Initialisation des variables 
		 frame = new JFrame("Formulaire ajout client");
		 this.upperMenu = upperMenu;
		 
		 //JFrame initialisation
	     frame.setContentPane(panel1);
	     frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	     frame.pack();
	     frame.setVisible(true);
	     frame.setSize(400,300);
	     panel1.setLayout(new BorderLayout(0, 0));
	        final JPanel panel2 = new JPanel();
	        panel2.setLayout(new BorderLayout(0, 0));
	        panel1.add(panel2, BorderLayout.WEST);
	        final JScrollPane scrollPane1 = new JScrollPane();
	        panel2.add(scrollPane1, BorderLayout.CENTER);
	        scrollPane1.setViewportView(list1);
	        final JPanel panel3 = new JPanel();
	        panel3.setLayout(new BorderLayout(0, 0));
	        panel1.add(panel3, BorderLayout.EAST);
	        annulerButton = new JButton();
	        annulerButton.setText("Annuler");
	        panel3.add(annulerButton, BorderLayout.SOUTH);
	        confirmerButton = new JButton();
	        confirmerButton.setText("Confirmer");
	        panel1.add(confirmerButton, BorderLayout.SOUTH);
	        final JLabel label1 = new JLabel();
	        label1.setText("Veuiller selectionner un vehicule");
	        panel1.add(label1, BorderLayout.NORTH);
	        
    }
    
    private void JListInitilisation()
    {
    	
    	ArrayList<Vehicule> listVehic;

    	
    	int noReser;
    	noReser = this.inputBoxInt("Veuillez entrer le numero de reservation ", "Ajout Location");
    	//On traite l'entrer
    	if(noReser == -1)//Si l'utilisateur veut annuler
    		this.toUpperMenu();
    	else
    	{
    		//On va fetch la liste des vehicule
    		listVehic = RegistreLocation.SaisiNoReservation(noReser);
    		
    		//On la transforme pour la JList
    		String[] tab = new String[listVehic.size()];
    		//Petit formatage pour la JList precisement
    		for (int i = 0; i < listVehic.size();i++) {
    		tab[i] = listVehic.get(i).getCategorie() + " " + listVehic.get(i).getKilometrage() + listVehic.get(i).getDate();
    	   }
    		list1 = new JList(tab);
    	}
   
    }
}
