import javax.swing.*;
import java.awt.*;

/**
 * 
 * @author Nicolas Dionne
 *
 * Menu du préposé utilisé pour l'ajout d'un client.
 * Le menu ce ferme que lorsque le préposé annule l'ajout d'un client ou lorsqu'il confirme l'ajout d'un client.
 * 
 *Fait avec l'aide de IntelliJ IDEA
 */
public class GUI_AjoutClient {
	JFrame frame = new JFrame("Formulaire ajout client");
	final JPanel panel1 = new JPanel();
	 private JTextField textField1;
	   private JTextField textField2;
	    private JTextField textField3;
	    private JFormattedTextField formattedTextField1;
	    private JFormattedTextField formattedTextField2;
	    private JFormattedTextField formattedTextField3;
	    private JPasswordField passwordField1;
	    private JButton confirmerAjoutButton;
	    private JButton annulerButton;
	public GUI_AjoutClient()
	{ 	
		 
		 //JFrame initialisation
	     frame.setContentPane(panel1);
	     frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	     frame.pack();
	     frame.setVisible(true);
	        panel1.setLayout(new GridBagLayout());
	        final JLabel label1 = new JLabel();
	      //  Font label1Font = this.$$$getFont$$$(null, -1, 16, label1.getFont());
	      //  if (label1Font != null) label1.setFont(label1Font);
	        label1.setHorizontalAlignment(11);
	        label1.setText("Nuémero carte Bancaire : ");
	        GridBagConstraints gbc;
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 8;
	        gbc.gridwidth = 9;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label1, gbc);
	        final JToolBar toolBar1 = new JToolBar();
	        gbc = new GridBagConstraints();
	        gbc.gridx = 2;
	        gbc.gridy = 9;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(toolBar1, gbc);
	        textField1 = new JTextField();
	       // Font textField1Font = this.$$$getFont$$$(null, -1, 16, textField1.getFont());
	       // if (textField1Font != null) textField1.setFont(textField1Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 1;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(textField1, gbc);
	        final JLabel label2 = new JLabel();
	       // Font label2Font = this.$$$getFont$$$(null, -1, 16, label2.getFont());
	      //  if (label2Font != null) label2.setFont(label2Font);
	        label2.setHorizontalAlignment(11);
	        label2.setText("Nom :");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 1;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label2, gbc);
	        textField2 = new JTextField();
	      //  Font textField2Font = this.$$$getFont$$$(null, -1, 16, textField2.getFont());
	       // if (textField2Font != null) textField2.setFont(textField2Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 2;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(textField2, gbc);
	        final JLabel label3 = new JLabel();
	       // Font label3Font = this.$$$getFont$$$(null, -1, 16, label3.getFont());
	       // if (label3Font != null) label3.setFont(label3Font);
	        label3.setHorizontalAlignment(11);
	        label3.setText("Prenom :");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 2;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label3, gbc);
	        textField3 = new JTextField();
	       // Font textField3Font = this.$$$getFont$$$(null, -1, 16, textField3.getFont());
	       // if (textField3Font != null) textField3.setFont(textField3Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 3;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(textField3, gbc);
	        final JLabel label4 = new JLabel();
	        //Font label4Font = this.$$$getFont$$$(null, -1, 16, label4.getFont());
	        //if (label4Font != null) label4.setFont(label4Font);
	        label4.setHorizontalAlignment(0);
	        label4.setHorizontalTextPosition(0);
	        label4.setText("Adresse : ");
	        label4.setToolTipText("Inserer en respectant le format numéro de maison, direction de rue, nom de rue, ville, province, ZipCode, pays");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 3;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label4, gbc);
	        final JLabel label5 = new JLabel();
	       // Font label5Font = this.$$$getFont$$$(null, -1, 16, label5.getFont());
	        //if (label5Font != null) label5.setFont(label5Font);
	        label5.setHorizontalAlignment(11);
	        label5.setText("Tél :     ");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 4;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label5, gbc);
	        formattedTextField1 = new JFormattedTextField();
	       // Font formattedTextField1Font = this.$$$getFont$$$(null, -1, 16, formattedTextField1.getFont());
	        //if (formattedTextField1Font != null) formattedTextField1.setFont(formattedTextField1Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 5;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(formattedTextField1, gbc);
	        formattedTextField2 = new JFormattedTextField();
	       // Font formattedTextField2Font = this.$$$getFont$$$(null, -1, 16, formattedTextField2.getFont());
	       // if (formattedTextField2Font != null) formattedTextField2.setFont(formattedTextField2Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 6;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(formattedTextField2, gbc);
	        formattedTextField3 = new JFormattedTextField();
	       // Font formattedTextField3Font = this.$$$getFont$$$(null, -1, 16, formattedTextField3.getFont());
	       // if (formattedTextField3Font != null) formattedTextField3.setFont(formattedTextField3Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 9;
	        gbc.gridy = 7;
	        gbc.gridwidth = 2;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(formattedTextField3, gbc);
	        final JLabel label6 = new JLabel();
	        //Font label6Font = this.$$$getFont$$$(null, -1, 16, label6.getFont());
	       // if (label6Font != null) label6.setFont(label6Font);
	        label6.setHorizontalAlignment(11);
	        label6.setText("Numéro de permis : ");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 7;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label6, gbc);
	        final JLabel label7 = new JLabel();
	        //Font label7Font = this.$$$getFont$$$(null, Font.ITALIC, 16, label7.getFont());
	       // if (label7Font != null) label7.setFont(label7Font);
	        label7.setText("Mobile");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 6;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label7, gbc);
	        final JLabel label8 = new JLabel();
	        //Font label8Font = this.$$$getFont$$$(null, Font.ITALIC, 16, label8.getFont());
	       //if (label8Font != null) label8.setFont(label8Font);
	        label8.setText("Domicile");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 5;
	        gbc.anchor = GridBagConstraints.EAST;
	        panel1.add(label8, gbc);
	        passwordField1 = new JPasswordField();
	        passwordField1.setColumns(9);
	        //Font passwordField1Font = this.$$$getFont$$$(null, -1, 16, passwordField1.getFont());
	       // if (passwordField1Font != null) passwordField1.setFont(passwordField1Font);
	        gbc = new GridBagConstraints();
	        gbc.gridx = 10;
	        gbc.gridy = 8;
	        gbc.anchor = GridBagConstraints.WEST;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(passwordField1, gbc);
	        confirmerAjoutButton = new JButton();
	        confirmerAjoutButton.setText("Confirmer Ajout");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 3;
	        gbc.gridy = 9;
	        gbc.gridwidth = 8;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(confirmerAjoutButton, gbc);
	        annulerButton = new JButton();
	        annulerButton.setText("Annuler");
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 9;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(annulerButton, gbc);
	        final JPanel spacer1 = new JPanel();
	        gbc = new GridBagConstraints();
	        gbc.gridx = 1;
	        gbc.gridy = 10;
	        gbc.fill = GridBagConstraints.VERTICAL;
	        panel1.add(spacer1, gbc);
	        final JPanel spacer2 = new JPanel();
	        gbc = new GridBagConstraints();
	        gbc.gridx = 11;
	        gbc.gridy = 6;
	        gbc.fill = GridBagConstraints.VERTICAL;
	        panel1.add(spacer2, gbc);
	        final JPanel spacer3 = new JPanel();
	        gbc = new GridBagConstraints();
	        gbc.gridx = 0;
	        gbc.gridy = 6;
	        gbc.fill = GridBagConstraints.VERTICAL;
	        panel1.add(spacer3, gbc);
	        final JPanel spacer4 = new JPanel();
	        gbc = new GridBagConstraints();
	        gbc.gridx = 5;
	        gbc.gridy = 0;
	        gbc.fill = GridBagConstraints.HORIZONTAL;
	        panel1.add(spacer4, gbc);
	        
	      //JFrame initialisation
		     frame.setContentPane(panel1);
		     frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		     frame.pack();
		     frame.setVisible(true);
	    }
}
